### ISSUE TITLE
Your App for F-Droid !!!

### ISSUE THREAD

**Issue by theScrabi** [prateekmedia/flutube#19]
Hei there, I just found this app on flatpak, and kind of like it :)
@prateekmedia It would be cool if you would put your app on the [F-Droid](https://f-droid.org/) repository to. This way you could also reach a broader audience :)

**Comment by prateekmedia** [comment]
Hi @theScrabi, I was very much inspired from your NewPipe app. Although it is awesome but I thought of creating a app that would be similar but Multi-platform.

Also thanks for the suggestion, I will try to upload it to F-droid although I have not done it before.

**Comment by prateekmedia** [comment]
https://gitlab.com/fdroid/rfp/-/issues/2002

**Comment by theScrabi** [comment]
Yea sure flutter is the future. If i had the time and the resources I would love to have a NewPipe front end completely written in flutter because of the system independence.

**Comment by Poussinou** [comment]
We're waiting for Fastlane ([example here](https://gitlab.com/-/snippets/1895688)), otherwise everything is ok to include this app on F-Droid ;)

**Comment by IzzySoft** [comment]
@prateekmedia in case you're not receiving GitLab notifications: can you please visit your RFP and answer the open questions, so we can proceed? Else the RFP would be closed for inactivity in 4 weeks, which would be a pity.

**Comment by IzzySoft** [comment]
Thanks @prateekmedia – I removed the closure label again. Wish you good progress!

**Comment by SecularSteve** [comment]
Is this still being worked on?

It's been over a year.

**Comment by prateekmedia** [comment]
@IzzySoft Anything blocked from my side for PsTube, I think you have already marked it as ready on gitlab

**Comment by prateekmedia** [comment]
@IzzySoft Please provide the skeleton YAML, I will create a MR

**Comment by IzzySoft** [comment]
OK, there you go with `metadata/com.prateekmedia.pstube.yml`. The build block will certainly need some adjustments, and the recipe expects Flutter to be added as a git submodule (always pointing to the Flutter version you need, so changing to a newer Flutter release would not require another MR at F-Droid for adjustments):

```yaml
AntiFeatures:
  - NonFreeNet
Categories:
  - Multimedia
License: GPL-3.0-or-later
AuthorName: Prateek Sunal
AuthorEmail: pankajsunal123@gmail.com
AuthorWebSite: https://prateekmedia.github.io/
SourceCode: https://github.com/prateekmedia/pstube
IssueTracker: https://github.com/prateekmedia/pstube/issues
Translation: https://hosted.weblate.org/engage/pstube/
Changelog: https://github.com/prateekmedia/pstube/releases

AutoName: PSTube

RepoType: git
Repo: https://github.com/prateekmedia/pstube

Builds:
  - versionName: 2.6.0
    versionCode: 2
    commit: 2.6.0
    submodules: true
    output: build/app/outputs/flutter-apk/app-release.apk
    rm:
      - .github
      - ios
      - linux
      - macos
      - test
      - web
      - windows
    prebuild:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - .flutter/bin/flutter config --no-analytics
      - .flutter/bin/flutter pub get
    scanignore:
      - .flutter/packages/flutter_tools/gradle/flutter.gradle
      - .flutter/bin/cache
    scandelete:
      - .flutter
      - .pub-cache
    build:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - .flutter/bin/flutter pub global activate intl_utils
      - .flutter/bin/flutter pub global run intl_utils:generate
      - .flutter/bin/flutter build apk --release

AutoUpdateMode: Version
UpdateCheckMode: Tags
UpdateCheckData: pubspec.yaml|version:\s.+\+(\d+)|.|version:\s(.+)\+
CurrentVersion: 2.6.0
CurrentVersionCode: 2
```

Note this is mostly copy-pasted from other recipes, I'm not that familiar with Flutter…

PS: Your `pubspec.yaml`  indicates `versionCode: 2`. That was a surprise to me, as there are definitely more than 2 releases available already. I'm puzzled how that matches…
